import {
  AlignLeft,
  Archive,
  ArchiveRestore,
  ArrowDown,
  ArrowDownToLine,
  ArrowLeft,
  ArrowUp,
  ArrowUpDown,
  BadgeCheck,
  Ban,
  Bell,
  BellOff,
  BellRing,
  Bold,
  Bookmark,
  BookOpenText,
  BookUser,
  Briefcase,
  Building2,
  Cake,
  CalendarCheck,
  CalendarClock,
  CalendarDays,
  CalendarPlus,
  CalendarSearch,
  CalendarX,
  Camera,
  Check,
  CheckCheck,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronsDownUp,
  CircleAlert,
  CircleCheck,
  CircleDashed,
  CircleHelp,
  CircleUserRound,
  Clock,
  Columns3,
  ContactRound,
  Copy,
  CopyX,
  Cpu,
  CreditCard,
  Crown,
  Dices,
  Download,
  Ellipsis,
  ExternalLink,
  Eye,
  EyeOff,
  File,
  FileArchive,
  FileAudio,
  FileCode,
  FileDiff,
  FileImage,
  FileOutput,
  FilePen,
  FilePlus,
  Files,
  FileSpreadsheet,
  FileText,
  FileVideo,
  FileX,
  Filter,
  Fingerprint,
  FlaskConical,
  Folder,
  FolderInput,
  FolderOpen,
  FolderPlus,
  FolderUp,
  Forward,
  Gauge,
  GitBranch,
  Globe,
  HardDrive,
  Heart,
  History,
  House,
  IdCard,
  Image,
  ImageOff,
  ImagePlus,
  Import,
  Inbox,
  Info,
  Italic,
  Keyboard,
  KeyRound,
  KeySquare,
  Languages,
  LayoutDashboard,
  LayoutGrid,
  LayoutList,
  Link,
  List,
  ListChecks,
  ListFilter,
  LoaderCircle,
  Lock,
  LockKeyhole,
  LockOpen,
  LogIn,
  LogOut,
  Mail,
  Mailbox,
  MailCheck,
  MailClock,
  MailOpen,
  MapPin,
  Maximize2,
  Menu,
  MessageSquarePlus,
  Minimize2,
  Minus,
  Monitor,
  Moon,
  Network,
  NotebookText,
  Palette,
  PanelLeft,
  PanelLeftClose,
  PanelLeftOpen,
  Paperclip,
  PartyPopper,
  Pencil,
  PenLine,
  Phone,
  Pin,
  Plane,
  Play,
  Plug,
  Plus,
  Printer,
  Puzzle,
  QrCode,
  Quote,
  RefreshCw,
  Repeat,
  Replace,
  Reply,
  ReplyAll,
  RotateCcw,
  Route,
  Save,
  SaveAll,
  Scaling,
  ScrollText,
  Search,
  Send,
  Server,
  Settings,
  Share2,
  ShieldAlert,
  ShieldCheck,
  ShieldQuestion,
  ShieldUser,
  Signature,
  SlidersHorizontal,
  Smartphone,
  Sparkles,
  SpellCheck,
  Square,
  SquareCheckBig,
  SquareTerminal,
  Star,
  StickyNote,
  Sun,
  TableOfContents,
  Tag,
  Tags,
  Timer,
  Trash2,
  TriangleAlert,
  Undo2,
  Unlink,
  Unplug,
  Upload,
  Usb,
  User,
  UserKey,
  UserPlus,
  Users,
  Vault,
  VenetianMask,
  Video,
  Volume2,
  VolumeX,
  WandSparkles,
  Wifi,
  WifiOff,
  X,
  Zap,
  ZoomIn,
  ZoomOut,
  type LucideIcon,
} from "lucide-react";
import { Android, DevicesSync, HandMirror, NyuFaceIcon, Paw, Tunnel } from "./suite.js";

/**
 * One meaning, one icon, in every app (docs/icons.md). Apps import from here instead of picking a
 * Lucide icon by taste, so "settings" is the same gear in UwUMail and UwUMirror and "delete" is
 * never a cross in one app and a bin in another.
 */
export const ICONS = {
  // Navigation and structure
  home: House,
  work: Briefcase,
  back: ArrowLeft,
  menu: Menu,
  sidebar: PanelLeft,
  expand: ChevronDown,
  next: ChevronRight,
  previous: ChevronLeft,
  more: Ellipsis,
  close: X,
  settings: Settings,
  search: Search,
  filter: Filter,
  sort: ArrowUpDown,
  // Actions
  add: Plus,
  edit: Pencil,
  delete: Trash2,
  archive: Archive,
  copy: Copy,
  share: Share2,
  send: Send,
  download: Download,
  upload: Upload,
  export: FileOutput,
  refresh: RefreshCw,
  undo: Undo2,
  reset: RotateCcw,
  history: History,
  pin: Pin,
  favorite: Star,
  openExternal: ExternalLink,
  link: Link,
  unlink: Unlink,
  start: Play,
  stop: Square,
  fullscreen: Maximize2,
  exitFullscreen: Minimize2,
  signIn: LogIn,
  signOut: LogOut,
  // Files and editing (from UwUNotes)
  file: File,
  newFile: FilePlus,
  folder: Folder,
  folderOpen: FolderOpen,
  newFolder: FolderPlus,
  save: Save,
  saveAll: SaveAll,
  closeFile: FileX,
  closeAll: CopyX,
  print: Printer,
  compare: FileDiff,
  replace: Replace,
  collapseAll: ChevronsDownUp,
  gitBranch: GitBranch,
  sidebarHide: PanelLeftClose,
  sidebarShow: PanelLeftOpen,
  preview: BookOpenText,
  outline: TableOfContents,
  bookmark: Bookmark,
  notebook: NotebookText,
  restore: ArchiveRestore,
  // Files on a host (from UwUSSH's file browser and UwURDP's drives)
  files: Files,
  parentFolder: FolderUp,
  drive: HardDrive,
  permissions: ShieldUser,
  // State and feedback
  done: Check,
  info: Info,
  help: CircleHelp,
  success: CircleCheck,
  warning: TriangleAlert,
  error: CircleAlert,
  notifications: Bell,
  notificationsOff: BellOff,
  show: Eye,
  hide: EyeOff,
  locked: Lock,
  unlocked: LockOpen,
  secret: KeyRound,
  pending: Clock,
  ai: Sparkles,
  // Settings pages
  account: User,
  language: Languages,
  lightTheme: Sun,
  darkTheme: Moon,
  sound: Volume2,
  soundOff: VolumeX,
  // Vault and secrets (from UwULock)
  vault: Vault,
  website: Globe,
  card: CreditCard,
  identity: IdCard,
  note: StickyNote,
  sshKey: KeySquare,
  wifi: Wifi,
  passkey: UserKey,
  securityKey: Usb,
  fingerprint: Fingerprint,
  masterPassword: LockKeyhole,
  oneTimeCode: Timer,
  generate: Dices,
  maskedAddress: VenetianMask,
  inbox: Inbox,
  travelMode: Plane,
  securityCheck: ShieldCheck,
  review: ListChecks,
  reminder: BellRing,
  organization: Building2,
  collection: LayoutGrid,
  qrCode: QrCode,
  import: Import,
  image: Image,
  moveUp: ArrowUp,
  moveDown: ArrowDown,
  // Remote access (from UwULock's SSH and RDP spaces)
  terminal: SquareTerminal,
  computer: Monitor,
  network: Network,
  // Sessions (from UwUSSH and UwURDP)
  server: Server,
  connect: Plug,
  disconnect: Unplug,
  tunnel: Tunnel,
  admin: Crown,
  keyboard: Keyboard,
  fit: Scaling,
  overview: LayoutDashboard,
  // Mail (from UwUMail)
  mail: Mail,
  compose: PenLine,
  reply: Reply,
  replyAll: ReplyAll,
  forward: Forward,
  drafts: FilePen,
  allMailboxes: Mailbox,
  unread: MailOpen,
  move: FolderInput,
  label: Tag,
  labels: Tags,
  spam: ShieldAlert,
  notSpam: MailCheck,
  spamCheck: ShieldQuestion,
  block: Ban,
  attachment: Paperclip,
  signature: Signature,
  sendLater: MailClock,
  imagesBlocked: ImageOff,
  redirect: Route,
  quote: Quote,
  rules: ListFilter,
  select: SquareCheckBig,
  selectAll: CheckCheck,
  automatic: Zap,
  offline: WifiOff,
  verified: BadgeCheck,
  score: Gauge,
  // Writing (UwUMail's composer and signature editor)
  bold: Bold,
  italic: Italic,
  bulletList: List,
  addImage: ImagePlus,
  insert: ArrowDownToLine,
  // AI assistant (from UwUMail; `ai` stays the sparkles)
  summary: ScrollText,
  rewrite: WandSparkles,
  adjust: SlidersHorizontal,
  proofread: SpellCheck,
  localModel: Cpu,
  experimental: FlaskConical,
  // Calendar (from UwUMail)
  calendar: CalendarDays,
  agenda: LayoutList,
  addEvent: CalendarPlus,
  findEvent: CalendarSearch,
  invitation: CalendarCheck,
  removeEvent: CalendarX,
  time: CalendarClock,
  repeat: Repeat,
  location: MapPin,
  description: AlignLeft,
  videoCall: Video,
  comment: MessageSquarePlus,
  maybe: CircleDashed,
  // Contacts (from UwUMail)
  contacts: BookUser,
  contact: ContactRound,
  addContact: UserPlus,
  people: Users,
  profile: CircleUserRound,
  phone: Phone,
  birthday: Cake,
  anniversary: Heart,
  celebration: PartyPopper,
  camera: Camera,
  // Kinds of files (UwUMail's attachments)
  document: FileText,
  imageFile: FileImage,
  codeFile: FileCode,
  spreadsheet: FileSpreadsheet,
  audioFile: FileAudio,
  videoFile: FileVideo,
  archiveFile: FileArchive,
  // App settings and controls (from UwUMail)
  appearance: Palette,
  addons: Puzzle,
  layout: Columns3,
  device: Smartphone,
  loading: LoaderCircle,
  zoomIn: ZoomIn,
  zoomOut: ZoomOut,
  mixed: Minus,
  // Suite icons (src/icons/suite.ts)
  android: Android,
  paw: Paw,
  nyu: NyuFaceIcon,
  mirror: HandMirror,
  sync: DevicesSync,
} satisfies Record<string, LucideIcon>;

export type IconMeaning = keyof typeof ICONS;
