import {
  Archive,
  ArchiveRestore,
  ArrowLeft,
  ArrowUpDown,
  Bell,
  BellOff,
  Bookmark,
  BookOpenText,
  Check,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronsDownUp,
  CircleAlert,
  CircleCheck,
  CircleHelp,
  Clock,
  Copy,
  CopyX,
  Download,
  Ellipsis,
  ExternalLink,
  Eye,
  EyeOff,
  File,
  FileDiff,
  FilePlus,
  FileX,
  Filter,
  Folder,
  FolderOpen,
  FolderPlus,
  GitBranch,
  History,
  House,
  Info,
  KeyRound,
  Languages,
  Link,
  Lock,
  LockOpen,
  LogOut,
  Maximize2,
  Menu,
  Minimize2,
  Moon,
  NotebookText,
  PanelLeft,
  PanelLeftClose,
  PanelLeftOpen,
  Pencil,
  Pin,
  Plus,
  Printer,
  RefreshCw,
  Replace,
  RotateCcw,
  Save,
  SaveAll,
  Search,
  Send,
  Settings,
  Share2,
  Sparkles,
  Star,
  Sun,
  TableOfContents,
  Trash2,
  TriangleAlert,
  Undo2,
  Unlink,
  Upload,
  User,
  X,
  type LucideIcon,
} from "lucide-react";
import { Android, DevicesSync, HandMirror, NyuFaceIcon, Paw } from "./suite.js";

/**
 * One meaning, one icon, in every app (docs/icons.md). Apps import from here instead of picking a
 * Lucide icon by taste, so "settings" is the same gear in UwUMail and UwUMirror and "delete" is
 * never a cross in one app and a bin in another.
 */
export const ICONS = {
  // Navigation and structure
  home: House,
  back: ArrowLeft,
  menu: Menu,
  sidebar: PanelLeft,
  expand: ChevronDown,
  next: ChevronRight,
  previous: ChevronLeft,
  more: Ellipsis,
  close: X,
  settings: Settings,
  search: Search,
  filter: Filter,
  sort: ArrowUpDown,
  // Actions
  add: Plus,
  edit: Pencil,
  delete: Trash2,
  archive: Archive,
  copy: Copy,
  share: Share2,
  send: Send,
  download: Download,
  upload: Upload,
  refresh: RefreshCw,
  undo: Undo2,
  reset: RotateCcw,
  history: History,
  pin: Pin,
  favorite: Star,
  openExternal: ExternalLink,
  link: Link,
  unlink: Unlink,
  fullscreen: Maximize2,
  exitFullscreen: Minimize2,
  signOut: LogOut,
  // Files and editing (from UwUNotes)
  file: File,
  newFile: FilePlus,
  folder: Folder,
  folderOpen: FolderOpen,
  newFolder: FolderPlus,
  save: Save,
  saveAll: SaveAll,
  closeFile: FileX,
  closeAll: CopyX,
  print: Printer,
  compare: FileDiff,
  replace: Replace,
  collapseAll: ChevronsDownUp,
  gitBranch: GitBranch,
  sidebarHide: PanelLeftClose,
  sidebarShow: PanelLeftOpen,
  preview: BookOpenText,
  outline: TableOfContents,
  bookmark: Bookmark,
  notebook: NotebookText,
  restore: ArchiveRestore,
  // State and feedback
  done: Check,
  info: Info,
  help: CircleHelp,
  success: CircleCheck,
  warning: TriangleAlert,
  error: CircleAlert,
  notifications: Bell,
  notificationsOff: BellOff,
  show: Eye,
  hide: EyeOff,
  locked: Lock,
  unlocked: LockOpen,
  secret: KeyRound,
  pending: Clock,
  ai: Sparkles,
  // Settings pages
  account: User,
  language: Languages,
  lightTheme: Sun,
  darkTheme: Moon,
  // Suite icons (src/icons/suite.ts)
  android: Android,
  paw: Paw,
  nyu: NyuFaceIcon,
  mirror: HandMirror,
  sync: DevicesSync,
} satisfies Record<string, LucideIcon>;

export type IconMeaning = keyof typeof ICONS;
