import {
  Archive,
  ArchiveRestore,
  ArrowDown,
  ArrowLeft,
  ArrowUp,
  ArrowUpDown,
  Bell,
  BellOff,
  BellRing,
  Bookmark,
  BookOpenText,
  Briefcase,
  Building2,
  Check,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronsDownUp,
  CircleAlert,
  CircleCheck,
  CircleHelp,
  Clock,
  Copy,
  CopyX,
  CreditCard,
  Crown,
  Dices,
  Download,
  Ellipsis,
  ExternalLink,
  Eye,
  EyeOff,
  File,
  FileDiff,
  FileOutput,
  FilePlus,
  Files,
  FileX,
  Filter,
  Fingerprint,
  Folder,
  FolderOpen,
  FolderPlus,
  FolderUp,
  GitBranch,
  Globe,
  HardDrive,
  History,
  House,
  IdCard,
  Image,
  Import,
  Inbox,
  Info,
  Keyboard,
  KeyRound,
  KeySquare,
  Languages,
  LayoutDashboard,
  LayoutGrid,
  Link,
  ListChecks,
  Lock,
  LockKeyhole,
  LockOpen,
  LogIn,
  LogOut,
  Maximize2,
  Menu,
  Minimize2,
  Monitor,
  Moon,
  Network,
  NotebookText,
  PanelLeft,
  PanelLeftClose,
  PanelLeftOpen,
  Pencil,
  Pin,
  Plane,
  Play,
  Plug,
  Plus,
  Printer,
  QrCode,
  RefreshCw,
  Replace,
  RotateCcw,
  Save,
  SaveAll,
  Scaling,
  Search,
  Send,
  Server,
  Settings,
  Share2,
  ShieldCheck,
  ShieldUser,
  Sparkles,
  Square,
  SquareTerminal,
  Star,
  StickyNote,
  Sun,
  TableOfContents,
  Timer,
  Trash2,
  TriangleAlert,
  Undo2,
  Unlink,
  Unplug,
  Upload,
  Usb,
  User,
  UserKey,
  Vault,
  VenetianMask,
  Volume2,
  VolumeX,
  Wifi,
  X,
  type LucideIcon,
} from "lucide-react";
import { Android, DevicesSync, HandMirror, NyuFaceIcon, Paw, Tunnel } from "./suite.js";

/**
 * One meaning, one icon, in every app (docs/icons.md). Apps import from here instead of picking a
 * Lucide icon by taste, so "settings" is the same gear in UwUMail and UwUMirror and "delete" is
 * never a cross in one app and a bin in another.
 */
export const ICONS = {
  // Navigation and structure
  home: House,
  work: Briefcase,
  back: ArrowLeft,
  menu: Menu,
  sidebar: PanelLeft,
  expand: ChevronDown,
  next: ChevronRight,
  previous: ChevronLeft,
  more: Ellipsis,
  close: X,
  settings: Settings,
  search: Search,
  filter: Filter,
  sort: ArrowUpDown,
  // Actions
  add: Plus,
  edit: Pencil,
  delete: Trash2,
  archive: Archive,
  copy: Copy,
  share: Share2,
  send: Send,
  download: Download,
  upload: Upload,
  export: FileOutput,
  refresh: RefreshCw,
  undo: Undo2,
  reset: RotateCcw,
  history: History,
  pin: Pin,
  favorite: Star,
  openExternal: ExternalLink,
  link: Link,
  unlink: Unlink,
  start: Play,
  stop: Square,
  fullscreen: Maximize2,
  exitFullscreen: Minimize2,
  signIn: LogIn,
  signOut: LogOut,
  // Files and editing (from UwUNotes)
  file: File,
  newFile: FilePlus,
  folder: Folder,
  folderOpen: FolderOpen,
  newFolder: FolderPlus,
  save: Save,
  saveAll: SaveAll,
  closeFile: FileX,
  closeAll: CopyX,
  print: Printer,
  compare: FileDiff,
  replace: Replace,
  collapseAll: ChevronsDownUp,
  gitBranch: GitBranch,
  sidebarHide: PanelLeftClose,
  sidebarShow: PanelLeftOpen,
  preview: BookOpenText,
  outline: TableOfContents,
  bookmark: Bookmark,
  notebook: NotebookText,
  restore: ArchiveRestore,
  // Files on a host (from UwUSSH's file browser and UwURDP's drives)
  files: Files,
  parentFolder: FolderUp,
  drive: HardDrive,
  permissions: ShieldUser,
  // State and feedback
  done: Check,
  info: Info,
  help: CircleHelp,
  success: CircleCheck,
  warning: TriangleAlert,
  error: CircleAlert,
  notifications: Bell,
  notificationsOff: BellOff,
  show: Eye,
  hide: EyeOff,
  locked: Lock,
  unlocked: LockOpen,
  secret: KeyRound,
  pending: Clock,
  ai: Sparkles,
  // Settings pages
  account: User,
  language: Languages,
  lightTheme: Sun,
  darkTheme: Moon,
  sound: Volume2,
  soundOff: VolumeX,
  // Vault and secrets (from UwULock)
  vault: Vault,
  website: Globe,
  card: CreditCard,
  identity: IdCard,
  note: StickyNote,
  sshKey: KeySquare,
  wifi: Wifi,
  passkey: UserKey,
  securityKey: Usb,
  fingerprint: Fingerprint,
  masterPassword: LockKeyhole,
  oneTimeCode: Timer,
  generate: Dices,
  maskedAddress: VenetianMask,
  inbox: Inbox,
  travelMode: Plane,
  securityCheck: ShieldCheck,
  review: ListChecks,
  reminder: BellRing,
  organization: Building2,
  collection: LayoutGrid,
  qrCode: QrCode,
  import: Import,
  image: Image,
  moveUp: ArrowUp,
  moveDown: ArrowDown,
  // Remote access (from UwULock's SSH and RDP spaces)
  terminal: SquareTerminal,
  computer: Monitor,
  network: Network,
  // Sessions (from UwUSSH and UwURDP)
  server: Server,
  connect: Plug,
  disconnect: Unplug,
  tunnel: Tunnel,
  admin: Crown,
  keyboard: Keyboard,
  fit: Scaling,
  overview: LayoutDashboard,
  // Suite icons (src/icons/suite.ts)
  android: Android,
  paw: Paw,
  nyu: NyuFaceIcon,
  mirror: HandMirror,
  sync: DevicesSync,
} satisfies Record<string, LucideIcon>;

export type IconMeaning = keyof typeof ICONS;
