// Writes the suite's own brand files from the Nyu catalogue (src/nyu/svg.ts):
//
//   node scripts/brand.mjs
//
//   brand/uwusuite-symbol.svg     the box cat on her own, with the white die-cut edge
//   brand/uwusuite-app-icon.svg   the box cat on the pastel tile (website, GitHub, store pages)
//
// The SVGs carry the sticker-edge CSS inline, so renderers without the app's stylesheet (resvg in
// `tauri icon`, browsers opening the file) draw the edge too.

import { writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { nyuSvg, VIEWBOX } from "../src/nyu/svg.ts";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");

export const EDGE_STYLE =
  '<style>.nyu-edge,.nyu-edge *{fill:#fff;stroke:#fff}.nyu-edge *{stroke-width:inherit}.nyu-edge [fill="none"],.nyu-edge [fill="none"] *{fill:none}.nyu-edge .no-edge{display:none}</style>';

function inner(svg) {
  return svg.replace(/^<svg[^>]*>/, "").replace(/<\/svg>$/, "");
}

const box = nyuSvg({ shell: "box", mood: "uwu", label: "", blink: false });
const [vx, vy, vw, vh] = VIEWBOX.box.split(" ").map(Number);

const symbol =
  `<svg xmlns="http://www.w3.org/2000/svg" viewBox="${VIEWBOX.box}" width="${vw * 2}" height="${vh * 2}" role="img" aria-label="UwUSuite">` +
  `<title>UwUSuite</title>${EDGE_STYLE}${inner(box)}</svg>\n`;

const star = (x, y, r) =>
  `<path d="M${x} ${y - r} Q${x + r * 0.18} ${y - r * 0.18} ${x + r} ${y} Q${x + r * 0.18} ${y + r * 0.18} ${x} ${y + r} Q${x - r * 0.18} ${y + r * 0.18} ${x - r} ${y} Q${x - r * 0.18} ${y - r * 0.18} ${x} ${y - r}Z" fill="#FFD66E" stroke="#4B1D3F" stroke-width="7" stroke-linejoin="round"/>`;
const heart = (x, y, s) =>
  `<path transform="translate(${x} ${y}) scale(${s})" d="M0 10 C-14 1 -20 -7 -18 -14 C-16 -21 -7 -23 -3 -17 L0 -13 L3 -17 C7 -23 16 -21 18 -14 C20 -7 14 1 0 10Z" fill="#FF6FA6" stroke="#4B1D3F" stroke-width="3.5" stroke-linejoin="round"/>`;

// Nyu at 1.62 × the 256 grid, centred a little low and tilted like every app icon.
const scale = 1.62;
const appIcon = `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 512" width="512" height="512" role="img" aria-label="UwUSuite app icon: Nyu peeking out of a box">
  <title>UwUSuite</title>
  <!-- Generated by scripts/brand.mjs from the Nyu catalogue. Tile and rules: docs/app-icons.md. -->
  <defs>
    <linearGradient id="uwu-bg" x1="0" y1="0" x2="0" y2="1">
      <stop offset="0" stop-color="#FFF3F8"/>
      <stop offset="1" stop-color="#FFD3E5"/>
    </linearGradient>
    <filter id="uwu-shadow" x="-20%" y="-20%" width="140%" height="150%">
      <feDropShadow dx="0" dy="10" stdDeviation="10" flood-color="#C2306F" flood-opacity="0.25"/>
    </filter>
  </defs>
  ${EDGE_STYLE}
  <rect width="512" height="512" rx="116" fill="url(#uwu-bg)"/>
  <g filter="url(#uwu-shadow)" transform="translate(254 268) rotate(-6) scale(${scale}) translate(${-(vx + vw / 2)} ${-(vy + vh / 2)})">${inner(box)}</g>
  ${star(420, 92, 28)}
  ${star(78, 128, 15)}
  ${heart(432, 440, 1.5)}
</svg>
`;

writeFileSync(join(root, "brand/uwusuite-symbol.svg"), symbol);
writeFileSync(join(root, "brand/uwusuite-app-icon.svg"), appIcon);
console.log("wrote brand/uwusuite-symbol.svg, brand/uwusuite-app-icon.svg");
